define((require, exports, module) => {
  return {
	'1' : 'Omamori',
	'2' : 'Omamori・Kyoku',
	'3' : 'Sennin Dango',
	'4' : 'Fuji Ofuda',
	'5' : 'Pine Ofuda',
	'6' : 'Bamboo Ofuda',
	'7' : 'Plum Ofuda',
	'8' : 'Help Token',
	'9' : 'Kiwame Training Recall Pigeon',
	'10' : 'Swords Room Extension Worker',
	'11' : 'Forge Extension Worker',
	'12' : 'Repairs Extension Worker',
	'13' : 'Koban Box (S)',
	'14' : 'Koban Box (M)',
	'15' : 'Koban Box (L)',
	'16' : 'Armory Extension Worker',
	'17' : 'Makunouchi Bento',
	'18' : 'Letter Set',
	'19' : 'Travel Garb',
	'20' : 'Travel Kit',
	'21' : 'Expedition Recall Pigeon',
	'22' : 'Army Provision',
	'23' : 'Double Box',
	'24' : 'Gramophone',
	'25' : 'Fue',
	'26' : 'Koto',
	'27' : 'Shamisen',
	'28' : 'Taiko',
	'29' : 'Suzu',
	'30' : 'Special Pass',
	'31' : 'Key',
	'32' : 'Treasure Chest Reset Pass',
	'33' : 'Investigation Tool Set',
	'34' : 'Triple Cage',
	'35' : 'Baton',
	'36' : 'Investigation Tool',
	'37' : 'One Bite Dango',
	'38' : 'One Bite Dango',
	'39' : 'Umeboshi',
	'40' : 'Umeboshi',
	'41' : 'Investigation Tool Set',
	'42' : 'Treasure Warehouse Key 2',
	'43' : 'Treasure Warehouse Key 3',
	'44' : 'Treasure Warehouse Key 4',
	'45' : 'Transfer Token',
	'46' : 'Transfer Token',
	'47' : 'Osaka Castle Underground Floor Map',
	'48' : 'Gramophone',
	'49' : 'Gramophone',
	'50' : 'Triple Box',
	'51' : 'Triple Box',
	'52' : 'Decuple Box',
	'53' : 'Decuple Box',
	'54' : 'Baton',
	'55' : 'Baton',
	'56' : 'Army Provision',
	'57' : 'Army Provision',
	'58' : 'Exchange Seal',
	'59' : 'Bean Thrower Ofuda',
	'60' : 'Lucky Beans',
	'61' : 'Investigation Tool',
	'62' : 'Investigation Tool',
	'63' : 'Treasure Chest Reset Pass',
	'64' : 'Triple Cage',
	'65' : 'Triple Cage',
	'66' : 'Decuple Cage',
	'67' : 'Decuple Cage',
	'68' : 'Compost',
	'69' : 'Special Fertilizer',
	'70' : 'Special Fertilizer',
	'71' : 'Tomato',
	'72' : 'Oriental Melon',
	'73' : 'Sunflower',
	'74' : 'Beltfish',
	'75' : 'Exchange Seal',
	'76' : 'Sweet Potatoe',
	'77' : 'Persimmon',
	'78' : 'Chrysanthemum',
	'79' : 'Shishamo',
	'80' : 'Dice',
	'81' : 'Lucky 7 Dice',
	'82' : 'Lucky 7 Dice',
	'83' : 'Shortcut Key',
	'84' : 'Shortcut Key',
	'85' : 'Dried Chestnuts',
	'86' : 'Dried Chestnuts',
	'87' : 'Special Investigation Tool',
	'88' : 'Special Investigation Tool',
	'89' : 'Kouhaku Manjuu',
	'90' : 'Buuterbur Bud',
	'91' : 'Sweet Orange',
	'92' : 'Plum',
	'93' : 'Clam',
	'94' : 'Sennin Dango',
	'95' : 'Sennin Dango',
	'96' : 'Makunouchi Bento',
	'97' : 'Makunouchi Bento',
	'98' : 'Fiddlehead Fern',
	'99' : 'Cherry',
	'100' : 'Wisteria',
	'101' : 'Sea Urchin',
	'1001' : 'White Konpeito'
  }
})