define((require, exports, module) => {
  return {
    MINOR_INJURY_PERCENTAGE: 0.9,
    MEDIUM_INJURY_PERCENTAGE: 0.645,
    SERIOUS_INJURY_PERCENTAGE: 0.305,
    DEATH_PERCENTAGE: 0,
    NONE: 0,
    MINOR_INJURY: 1,
    MEDIUM_INJURY: 2,
    SERIOUS_INJURY: 3,
    DEATH: 4
  }
})